// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: net/outbe/common/v1/date.proto
// Protobuf Java Version: 4.33.0

package net.outbe.common.v1;

@com.google.protobuf.Generated
public final class DateOuterClass extends com.google.protobuf.GeneratedFile {
  private DateOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "DateOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.outbe.common.v1.Date)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     * </pre>
     *
     * <code>uint32 year = 1 [json_name = "year"];</code>
     * @return The year.
     */
    int getYear();

    /**
     * <pre>
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     * </pre>
     *
     * <code>uint32 month = 2 [json_name = "month"];</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <pre>
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     * </pre>
     *
     * <code>uint32 day = 3 [json_name = "day"];</code>
     * @return The day.
     */
    int getDay();
  }
  /**
   * Protobuf type {@code net.outbe.common.v1.Date}
   */
  public static final class Date extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.outbe.common.v1.Date)
      DateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "Date");
    }
    // Use Date.newBuilder() to construct.
    private Date(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Date() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.outbe.common.v1.DateOuterClass.internal_static_net_outbe_common_v1_Date_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.outbe.common.v1.DateOuterClass.internal_static_net_outbe_common_v1_Date_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.outbe.common.v1.DateOuterClass.Date.class, net.outbe.common.v1.DateOuterClass.Date.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_ = 0;
    /**
     * <pre>
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
     * a year.
     * </pre>
     *
     * <code>uint32 year = 1 [json_name = "year"];</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_ = 0;
    /**
     * <pre>
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
     * month and day.
     * </pre>
     *
     * <code>uint32 month = 2 [json_name = "month"];</code>
     * @return The month.
     */
    @java.lang.Override
    public int getMonth() {
      return month_;
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private int day_ = 0;
    /**
     * <pre>
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
     * to specify a year by itself or a year and month where the day isn't
     * significant.
     * </pre>
     *
     * <code>uint32 day = 3 [json_name = "day"];</code>
     * @return The day.
     */
    @java.lang.Override
    public int getDay() {
      return day_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (year_ != 0) {
        output.writeUInt32(1, year_);
      }
      if (month_ != 0) {
        output.writeUInt32(2, month_);
      }
      if (day_ != 0) {
        output.writeUInt32(3, day_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, year_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, month_);
      }
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, day_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.outbe.common.v1.DateOuterClass.Date)) {
        return super.equals(obj);
      }
      net.outbe.common.v1.DateOuterClass.Date other = (net.outbe.common.v1.DateOuterClass.Date) obj;

      if (getYear()
          != other.getYear()) return false;
      if (getMonth()
          != other.getMonth()) return false;
      if (getDay()
          != other.getDay()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static net.outbe.common.v1.DateOuterClass.Date parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static net.outbe.common.v1.DateOuterClass.Date parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static net.outbe.common.v1.DateOuterClass.Date parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.outbe.common.v1.DateOuterClass.Date prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.outbe.common.v1.Date}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.outbe.common.v1.Date)
        net.outbe.common.v1.DateOuterClass.DateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.outbe.common.v1.DateOuterClass.internal_static_net_outbe_common_v1_Date_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.outbe.common.v1.DateOuterClass.internal_static_net_outbe_common_v1_Date_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.outbe.common.v1.DateOuterClass.Date.class, net.outbe.common.v1.DateOuterClass.Date.Builder.class);
      }

      // Construct using net.outbe.common.v1.DateOuterClass.Date.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        year_ = 0;
        month_ = 0;
        day_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.outbe.common.v1.DateOuterClass.internal_static_net_outbe_common_v1_Date_descriptor;
      }

      @java.lang.Override
      public net.outbe.common.v1.DateOuterClass.Date getDefaultInstanceForType() {
        return net.outbe.common.v1.DateOuterClass.Date.getDefaultInstance();
      }

      @java.lang.Override
      public net.outbe.common.v1.DateOuterClass.Date build() {
        net.outbe.common.v1.DateOuterClass.Date result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.outbe.common.v1.DateOuterClass.Date buildPartial() {
        net.outbe.common.v1.DateOuterClass.Date result = new net.outbe.common.v1.DateOuterClass.Date(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(net.outbe.common.v1.DateOuterClass.Date result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.year_ = year_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.month_ = month_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.day_ = day_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.outbe.common.v1.DateOuterClass.Date) {
          return mergeFrom((net.outbe.common.v1.DateOuterClass.Date)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.outbe.common.v1.DateOuterClass.Date other) {
        if (other == net.outbe.common.v1.DateOuterClass.Date.getDefaultInstance()) return this;
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                year_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                month_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                day_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int year_ ;
      /**
       * <pre>
       * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
       * a year.
       * </pre>
       *
       * <code>uint32 year = 1 [json_name = "year"];</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <pre>
       * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
       * a year.
       * </pre>
       *
       * <code>uint32 year = 1 [json_name = "year"];</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {

        year_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Year of the date. Must be from 1 to 9999, or 0 to specify a date without
       * a year.
       * </pre>
       *
       * <code>uint32 year = 1 [json_name = "year"];</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <pre>
       * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
       * month and day.
       * </pre>
       *
       * <code>uint32 month = 2 [json_name = "month"];</code>
       * @return The month.
       */
      @java.lang.Override
      public int getMonth() {
        return month_;
      }
      /**
       * <pre>
       * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
       * month and day.
       * </pre>
       *
       * <code>uint32 month = 2 [json_name = "month"];</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {

        month_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Month of a year. Must be from 1 to 12, or 0 to specify a year without a
       * month and day.
       * </pre>
       *
       * <code>uint32 month = 2 [json_name = "month"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        month_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <pre>
       * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
       * to specify a year by itself or a year and month where the day isn't
       * significant.
       * </pre>
       *
       * <code>uint32 day = 3 [json_name = "day"];</code>
       * @return The day.
       */
      @java.lang.Override
      public int getDay() {
        return day_;
      }
      /**
       * <pre>
       * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
       * to specify a year by itself or a year and month where the day isn't
       * significant.
       * </pre>
       *
       * <code>uint32 day = 3 [json_name = "day"];</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {

        day_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
       * to specify a year by itself or a year and month where the day isn't
       * significant.
       * </pre>
       *
       * <code>uint32 day = 3 [json_name = "day"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        day_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.outbe.common.v1.Date)
    }

    // @@protoc_insertion_point(class_scope:net.outbe.common.v1.Date)
    private static final net.outbe.common.v1.DateOuterClass.Date DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.outbe.common.v1.DateOuterClass.Date();
    }

    public static net.outbe.common.v1.DateOuterClass.Date getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Date>
        PARSER = new com.google.protobuf.AbstractParser<Date>() {
      @java.lang.Override
      public Date parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Date> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Date> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.outbe.common.v1.DateOuterClass.Date getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_outbe_common_v1_Date_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_outbe_common_v1_Date_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036net/outbe/common/v1/date.proto\022\023net.ou" +
      "tbe.common.v1\"B\n\004Date\022\022\n\004year\030\001 \001(\rR\004yea" +
      "r\022\024\n\005month\030\002 \001(\rR\005month\022\020\n\003day\030\003 \001(\rR\003da" +
      "yB6Z4github.com/outbe/fingerprinting/cli" +
      "ents/go/common/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_outbe_common_v1_Date_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_net_outbe_common_v1_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_outbe_common_v1_Date_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
